---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: nginx
        api_version: v1
        kind: Namespace
        state: present

    - name: Create a Deployment by reading the definition from a local file
      kubernetes.core.k8s:
        state: present
        src: deployment-nginx.yml
