---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Add EE to the controller instance
      awx.awx.execution_environment:
        name: "My EE"
        image: sonorous34/k8s-awx:lts
