---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: 01-Create harbor namespace
      kubernetes.core.k8s:
        name: harbor
        api_version: v1
        kind: Namespace
        state: present

    - name: 02-Deploy Harbor Helm
      kubernetes.core.helm:
        name: harbor
        chart_ref: harbor/harbor
        release_namespace: harbor
