---
- name: Update Projects on Controller
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    controller_validate_certs: false
    controller_hostname: localhost
    controller_username: admin
    controller_password: admin1234!

  collections:
    - awx.awx

  pre_tasks:
    - name: Update Projects on Controller
    controller_projects:
      - name: k8s-project
        scm_type: git
        scm_url: https://github.com/sonorous34/awx-k8s-niginx.git
        scm_branch: main
        scm_clean: true
        description: awx-nginx
        organization: k8s-org
        update: true
        wait: true
